#!/bin/sh
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

# exit immediately on error
set -e
# find the .git directory
dir="`git rev-parse --git-dir`"
# remove the temporary tags file on script exit
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
# rename temporary tags file to ".git/tags"
mv "$dir/$$.tags" "$dir/tags"
